-- The applied schema. `npm run db:migrate` runs this file, and it is idempotent.
--
-- THIS SUPERSEDES `src/momentum/schema.sql`, which was written as a sketch before any of it
-- was wired up. Two things changed on contact with the code and both are worth stating,
-- because the sketch looks more "properly relational" and is wrong:
--
--   1. CONFIG IS A DOCUMENT, NOT COLUMNS. The sketch gave `momentum_config` a fixed column
--      per section (weights, scoring, confidence, thresholds, universe, refresh, output).
--      `MomentumConfig` has since grown `signal`, `ranking` and `conviction`, and it will
--      grow again. Every one of those would have been a migration, and — worse — a config
--      saved before a section existed would come back missing it, which is precisely the
--      failure `config.repository.ts` merges over defaults to avoid. So config is stored as
--      one JSONB document per version, keyed by module.
--
--   2. SNAPSHOTS ARE NOT HERE AT ALL. The sketch had `momentum_snapshot` as an insert per
--      board. The momentum scan runs every 15s and the pullback scan every 30s, which is
--      1,500 + 750 boards a session at 1.6 MB and 2.3 MB each — about 4 GB a day of TOASTed
--      JSONB, to store something that is overwritten seconds later and only ever read as
--      "the last one". That belongs on disk, where an atomic rename already handles it.
--      `snapshot.repository.ts` keeps the file driver.
--
-- What IS here is the two tables that are genuinely append-mostly and genuinely want to be
-- queried across, plus config for the audit trail.

BEGIN;

-- ------------------------------------------------------------------- app_config ----
-- One row per saved version, per module. The active config is the highest version for a key.
--
-- Versioned rather than updated in place, which is what the sketch wanted and the one part of
-- it that survives intact: a board carries the config version it was scored under, and being
-- able to answer "what were the weights when this ranked first?" is the difference between an
-- audit trail and a shrug. Configs change by hand, a few times a month, so keeping every
-- version costs nothing worth measuring.
CREATE TABLE IF NOT EXISTS app_config (
    key         TEXT        NOT NULL,          -- 'config' (momentum) | 'pullback_config'
    version     INTEGER     NOT NULL,
    value       JSONB       NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by  TEXT        NOT NULL DEFAULT 'unknown',
    PRIMARY KEY (key, version)
);

CREATE INDEX IF NOT EXISTS app_config_key_version_idx
    ON app_config (key, version DESC);

-- --------------------------------------------------------------- momentum_history ----
-- One row per symbol per session. ~208 symbols x ~250 sessions = ~52k rows a year.
--
-- `atm_iv` is the whole reason this table exists. Upstox publishes implied volatility as of
-- NOW and has no historical-IV endpoint at any tier, so IV Rank and IV Percentile are only
-- ever computable from a series this table accumulates. See `data/history.repository.ts`.
--
-- The file driver trims to 520 days per symbol so the JSON cannot grow without bound. That
-- limit is a property of rewriting a whole file on every write, not of the data, so it is not
-- reproduced here — a longer IV history makes IV Rank strictly better and 52k rows a year is
-- nothing. Prune explicitly if it ever matters.
CREATE TABLE IF NOT EXISTS momentum_history (
    symbol       TEXT           NOT NULL,
    day          DATE           NOT NULL,
    close        NUMERIC(14, 4) NOT NULL,
    score        NUMERIC(6, 2)  NOT NULL,
    direction    TEXT           NOT NULL CHECK (direction IN ('Bullish', 'Bearish', 'Neutral')),
    rvol         NUMERIC(10, 3),
    atm_iv       NUMERIC(10, 3),
    hv20         NUMERIC(10, 3),
    futures_oi   BIGINT,
    recorded_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
    PRIMARY KEY (symbol, day)
);

CREATE INDEX IF NOT EXISTS momentum_history_symbol_day_idx
    ON momentum_history (symbol, day DESC);

-- The IV-rank query this table exists to serve:
--   SELECT atm_iv FROM momentum_history
--    WHERE symbol = $1 AND atm_iv IS NOT NULL
--    ORDER BY day DESC LIMIT 252;

-- --------------------------------------------------------------- pullback_signal ----
-- Every fired signal, with the outcome tracked to settlement.
--
-- The outcome is columns rather than a JSONB blob because `settle()` updates it on every scan
-- for every open trade, and because `state` is the column all the interesting questions filter
-- on. `option` stays JSONB — it is a three-field record that is only ever read whole.
--
-- NOTE the natural key. `id` is generated by the scanner from symbol + timeframe + the
-- confirmation bar, so re-scanning the same confirmation produces the same id. That is what
-- makes `record()` idempotent, and it is enforced here as the primary key rather than trusted
-- to the caller: the scan runs every 30 seconds and a confirmation stays valid across several
-- of them, so the duplicate insert is the COMMON path, not an edge case.
CREATE TABLE IF NOT EXISTS pullback_signal (
    id              TEXT           PRIMARY KEY,
    day             DATE           NOT NULL,
    symbol          TEXT           NOT NULL,
    timeframe       INTEGER        NOT NULL,
    direction       SMALLINT       NOT NULL CHECK (direction IN (1, -1)),
    fired_at        BIGINT         NOT NULL,   -- epoch ms, as the engine carries it
    entry           NUMERIC(14, 4) NOT NULL,
    stop            NUMERIC(14, 4) NOT NULL,
    target          NUMERIC(14, 4) NOT NULL,
    score           NUMERIC(6, 2)  NOT NULL,
    band            TEXT           NOT NULL,
    entry_kind      TEXT           NOT NULL,
    option          JSONB,
    outcome_state   TEXT           NOT NULL,
    max_favourable  NUMERIC(14, 4) NOT NULL,
    max_adverse     NUMERIC(14, 4) NOT NULL,
    realised_r      NUMERIC(10, 4),
    closed_at       BIGINT,
    note            TEXT
);

CREATE INDEX IF NOT EXISTS pullback_signal_day_idx
    ON pullback_signal (day DESC, fired_at);

-- Serves `lastFiredAt(symbol, timeframe)` — the cooldown's memory.
CREATE INDEX IF NOT EXISTS pullback_signal_symbol_tf_idx
    ON pullback_signal (symbol, timeframe, fired_at DESC);

-- Serves `open()`. Partial, because open signals are a handful of rows out of the whole table
-- and this keeps the index that size rather than the table's.
CREATE INDEX IF NOT EXISTS pullback_signal_open_idx
    ON pullback_signal (fired_at) WHERE outcome_state = 'Open';

-- ---------------------------------------------------------------- candle_archive ----
-- The 1-minute bar archive. This is the table that makes backtesting over real history
-- possible, and it is the one place market data is allowed to accumulate without bound.
--
-- WHY THIS EARNS ITS PLACE where `pullback_seed` does not. The seed is a ROLLING window —
-- twenty calendar days, rebuilt daily, thrown away and re-fetched. This is an ARCHIVE: append
-- only, never re-fetched, and it grows into something Upstox will not sell you back. Upstox
-- serves a 1-minute range of at most ~30 calendar days per request and rate limits to 2000
-- requests per 30 minutes, so a year of 1-minute history for the full universe cannot simply
-- be downloaded on demand — it has to be accumulated a session at a time. That is exactly
-- what a database is for and exactly what a rolling cache cannot do.
--
-- ONE ROW PER (symbol, day), NOT PER BAR. A row per bar is 212 symbols x 375 minutes x 250
-- sessions = ~20 MILLION rows a year, and it buys nothing: every reader of this table wants a
-- contiguous range for one symbol, never an individual bar and never `WHERE close > 100`. One
-- row per symbol-day is ~53,000 rows a year for the same data and is the shape the access
-- pattern actually has.
--
-- ONLY 1-MINUTE IS STORED. The 3, 5 and 15 minute frames are exact sums of these (see
-- `pullback/data/frames.ts`), so storing them would be storing a derivation — four times the
-- bytes, and four things to disagree with each other after a backfill.
--
-- `bars` LAYOUT — 22 bytes per bar, little-endian, ascending by minute:
--     offset 0   int16   minute of session (0 = the 09:15 bar)
--     offset 2   int32   open   in PAISE (rupees x 100)
--     offset 6   int32   high   in paise
--     offset 10  int32   low    in paise
--     offset 14  int32   close  in paise
--     offset 18  int32   volume in shares
--
-- Prices are integer paise rather than float32 deliberately: float32 carries ~7 significant
-- digits and a five-figure index level with two decimals needs eight, so a NIFTY bar would
-- round in the last paisa — invisible on a chart and not invisible to a backtest that decides
-- whether a stop was touched. int32 paise is exact to ₹21,474,836, which is four times the
-- highest-priced instrument on the exchange.
--
-- Turnover and the epoch stamp are NOT stored because both are derivable and storing them
-- would let them drift: `at` is the session open plus `minute`, and turnover for an exchange
-- candle is ((high + low + close) / 3) x volume, which is precisely what `fromCandle` computes.
CREATE TABLE IF NOT EXISTS candle_archive (
    symbol       TEXT        NOT NULL,
    day          DATE        NOT NULL,
    interval_min SMALLINT    NOT NULL DEFAULT 1,
    bars         BYTEA       NOT NULL,
    bar_count    INTEGER     NOT NULL,
    archived_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (symbol, day, interval_min)
);

-- The only query shape this table has: one symbol, a date range, oldest first.
CREATE INDEX IF NOT EXISTS candle_archive_symbol_day_idx
    ON candle_archive (symbol, interval_min, day);

-- Answers "what do I already have?" without reading a single blob — which is what makes an
-- incremental archive job cheap enough to run every evening.
CREATE INDEX IF NOT EXISTS candle_archive_day_idx
    ON candle_archive (day);

COMMIT;
