// Fill the trade journal with sample rows, so the page can be reviewed before a real signal has
// ever been recorded.  Run: npm run seed-journal      Undo: npm run seed-journal -- --clear
//
// WHY THIS EXISTS AND WHY IT IS TEMPORARY. The journal only gains rows when an alert channel
// fires and prices a contract; nothing is backfilled. That is correct behaviour and it means a
// fresh install shows an empty page with no way to tell a working journal from a broken one.
// This writes rows that look like real ones so the layout, the totals, the shadow cards, the
// channel filter and the edit dialog can all be seen at once.
//
// EVERY NUMBER IN HERE IS INVENTED. The symbols and spot prices are real and taken from the
// 2026-08-24 snapshot, so the strikes look sane; the premiums, fills, outcomes and excursions are
// generated. Nothing here was measured and none of it should ever be quoted as performance.
//
// DELETION IS THE POINT, so it is built in rather than left as a chore:
//
//   EVERY SAMPLE ROW CARRIES `MARKER` IN ITS NOTE, and that — not the id list — is what `--clear`
//   matches on. The first cut of this tool removed "whatever the generator produces today",
//   which was wrong in a way that only showed up once: editing the roster changed the ids, so a
//   clear after an edit deleted the rows the NEW code would have written and orphaned the ones
//   actually on disk. A real trade never carries the marker, so matching on it is both surgical
//   and immune to this file being edited between the seed and the clear.
//
//   IT CLEARS BOTH HALVES OF THE RECORD. `api/.env` has a DATABASE_URL, so the journal runs as a
//   mirror: local disk plus Neon. `journalBoot()` pushes local history the database has not seen
//   on the first journal request, which means these rows reach Neon as soon as the page is opened
//   — deleting the local file alone would leave them in the shared record and they would come
//   back on the next read. `--clear` deletes from disk, from Postgres, and from the retry queue.

import '../src/env.js';

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { closePool, databaseUrl, getPool } from '../src/momentum/journal/postgres.js';
import type { ExitReason, JournalChannel, JournalTrade } from '../src/momentum/journal/types.js';

const here = path.dirname(fileURLToPath(import.meta.url));
const CACHE = path.join(here, '..', '.cache', 'momentum');

/* ------------------------------------------------------------------------- the shape --- */

const FROM = '2026-08-03';
const TO = '2026-08-24';
const EXPIRY = '2026-08-27';

/**
 * What makes a row removable, and why there are two of them.
 *
 * `KEY_MARKER` is the one that counts. It sits in `contract.instrumentKey`, which no code path can
 * change: `JournalPatch` accepts only entry premium, exit premium, lots, note and reset, so the
 * contract is immutable once written. A real Upstox instrument key never looks like this.
 *
 * `MARKER` in the note is a convenience for reading a row on screen and NOT a reliable key — the
 * edit dialog sends `note` on every save, so using the fill editor on a sample row wipes it. That
 * is not hypothetical: it stranded a row through a `--clear` during review, which is why the
 * instrument key became the primary match rather than the note.
 *
 * Never change either without clearing first — an old marker on disk and a new one in the code is
 * exactly the orphaning these exist to prevent.
 */
const KEY_MARKER = 'NSE_FO|SAMPLE-';
const MARKER = 'SAMPLE ROW — generated by tools/journal-seed.ts';

/** Months a clear should sweep, whatever the generator currently produces. */
const SWEEP_MONTHS = ['2026-07', '2026-08', '2026-09'];

/** Read the same way the app reads them, so the money columns match what the page computes. */
const CHARGE_PER_LOT = Number(process.env.JOURNAL_CHARGE_PER_LOT) || 120;
const LOTS = Number(process.env.JOURNAL_LOTS) || 1;
const TP = 0.80;
const SL = 0.50;
const SQUARE_OFF_MIN = 360;

/** The same three alternatives `SHADOW` in journal.ts scores every trade under. */
const SHADOW = [
  { name: '+30/-15', tp: 0.30, sl: 0.15 },
  { name: '+30/-50', tp: 0.30, sl: 0.50 },
  { name: '+60/-30', tp: 0.60, sl: 0.30 },
];

/** Real symbols and real 2026-08-24 closes. Lot sizes are the NSE ones for those prices. */
const ROSTER: Array<{ symbol: string; spot: number; lotSize: number; step: number }> = [
  { symbol: 'RELIANCE', spot: 1309.8, lotSize: 500, step: 10 },
  { symbol: 'HDFCBANK', spot: 729, lotSize: 550, step: 10 },
  { symbol: 'ICICIBANK', spot: 1415, lotSize: 700, step: 10 },
  { symbol: 'SBIN', spot: 1039.5, lotSize: 750, step: 10 },
  { symbol: 'INFY', spot: 1130, lotSize: 400, step: 20 },
  { symbol: 'AXISBANK', spot: 1236, lotSize: 625, step: 10 },
  { symbol: 'BAJFINANCE', spot: 1077, lotSize: 750, step: 10 },
  { symbol: 'HINDALCO', spot: 1058.5, lotSize: 700, step: 10 },
  { symbol: 'MUTHOOTFIN', spot: 3209, lotSize: 275, step: 50 },
  { symbol: 'SIEMENS', spot: 4114, lotSize: 150, step: 50 },
  { symbol: 'DIXON', spot: 14570, lotSize: 50, step: 250 },
  { symbol: 'GLENMARK', spot: 2390.7, lotSize: 250, step: 25 },
  { symbol: 'HAL', spot: 4906, lotSize: 150, step: 50 },
  { symbol: 'BEL', spot: 409, lotSize: 1900, step: 5 },
  { symbol: 'TCS', spot: 2284.1, lotSize: 175, step: 20 },
  { symbol: 'MARUTI', spot: 13620, lotSize: 50, step: 100 },
  { symbol: 'CANBK', spot: 127.3, lotSize: 6750, step: 5 },
  { symbol: 'RVNL', spot: 221.7, lotSize: 2600, step: 5 },
];

/**
 * Symbols that actually alerted on the last seeded day, kept out of it.
 *
 * A trade id is `day:channel:symbol`, so a sample row on DIXON today would occupy the id the real
 * displacement alert needs, and `recordEntries` would skip the real one as already journalled.
 */
const TAKEN_ON_LAST_DAY = new Set(['DIXON', 'MUTHOOTFIN', 'SIEMENS']);

/* -------------------------------------------------------------------- the determinism --- */

/** Fixed-seed PRNG. No clock anywhere in this file — `--clear` depends on that. */
function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const between = (r: () => number, lo: number, hi: number): number => lo + r() * (hi - lo);
const pick = <T>(r: () => number, xs: T[]): T => xs[Math.floor(r() * xs.length) % xs.length];
const round = (n: number, dp = 2): number => +n.toFixed(dp);

/** Weekdays in [FROM, TO]. Holidays are not netted out; a sample journal does not need them. */
function sessionDays(): string[] {
  const out: string[] = [];
  for (let t = Date.parse(`${FROM}T00:00:00Z`); t <= Date.parse(`${TO}T00:00:00Z`); t += 86_400_000) {
    const d = new Date(t);
    if (d.getUTCDay() !== 0 && d.getUTCDay() !== 6) out.push(d.toISOString().slice(0, 10));
  }
  return out;
}

/** Epoch ms for a minute of an IST session. 0 = 09:15 IST. */
const atOf = (day: string, minute: number): number =>
  Date.parse(`${day}T00:00:00Z`) + (9 * 60 + 15 + minute - 330) * 60_000;

/* ------------------------------------------------------------------------ the outcomes --- */

type Outcome = 'target' | 'stop' | 'untracked' | 'won' | 'lost';

/**
 * Outcomes are DEALT FROM A FIXED QUOTA, not drawn per trade.
 *
 * A per-trade coin flip was the first cut and it was the wrong tool. Thirty trades is far too few
 * for a 56% draw to land near 56% — one seed produced 80% winners — and the number a sample
 * journal puts at the top of the page is the one thing about it a reader will remember. So the
 * proportions are declared here and merely shuffled into an order.
 *
 * They are set near what the displacement study actually reported — about 60% of trades ending
 * profitable and roughly one in ten stopped out — so the page shows a plausible month rather than
 * a flattering one. It is still invented data and proves nothing.
 */
const QUOTA: Array<{ outcome: Outcome; share: number }> = [
  { outcome: 'target', share: 0.12 },      // ran to +80%
  { outcome: 'stop', share: 0.16 },        // hit -50%
  { outcome: 'untracked', share: 0.08 },   // chain never priced it
  { outcome: 'won', share: 0.44 },         // squared off green
  { outcome: 'lost', share: 0.20 },        // squared off red
];

/** `n` outcomes in the declared proportions, shuffled deterministically. */
function dealOutcomes(n: number, r: () => number): Outcome[] {
  const deck: Outcome[] = [];
  for (const q of QUOTA) for (let i = 0; i < Math.round(q.share * n); i++) deck.push(q.outcome);
  while (deck.length < n) deck.push('won');
  deck.length = n;
  for (let i = deck.length - 1; i > 0; i--) {
    const j = Math.floor(r() * (i + 1));
    [deck[i], deck[j]] = [deck[j], deck[i]];
  }
  return deck;
}

/* ---------------------------------------------------------------------- the generator --- */

function build(): JournalTrade[] {
  const days = sessionDays();

  // How many trades each day gets, decided on its own stream so that changing anything about how
  // a trade is built cannot shift the day pattern.
  const rDays = rng(20260824);
  const counts: number[] = days.map(() => {
    // 0-4 a day, with the odd quiet session — the displacement study averaged 2.8 signals a day
    // and this lands near 2, which is about right once the other two channels are mixed in.
    const roll = rDays();
    return roll < 0.08 ? 0 : roll < 0.35 ? 1 : roll < 0.70 ? 2 : roll < 0.90 ? 3 : 4;
  });

  const deck = dealOutcomes(counts.reduce((a, b) => a + b, 0), rng(77));
  let dealt = 0;

  const r = rng(31337);
  const out: JournalTrade[] = [];

  days.forEach((day, di) => {
    const lastDay = di === days.length - 1;
    const used = new Set<string>();

    for (let i = 0; i < counts[di]; i++) {
      const channel: JournalChannel =
        r() < 0.45 ? 'displacement' : r() < 0.72 ? 'trend-day' : 'ignition';

      let tries = 0;
      let sym = pick(r, ROSTER);
      const blocked = (s: string): boolean =>
        used.has(`${channel}:${s}`) || (lastDay && TAKEN_ON_LAST_DAY.has(s));
      while (blocked(sym.symbol) && tries++ < 40) sym = pick(r, ROSTER);
      if (blocked(sym.symbol)) continue;
      used.add(`${channel}:${sym.symbol}`);

      const direction: 1 | -1 = r() < 0.55 ? 1 : -1;
      const type = direction === 1 ? 'CE' : 'PE';
      const entryMinute = Math.round(
        channel === 'displacement' ? between(r, 12, 45)
          : channel === 'trend-day' ? between(r, 75, 240)
            : between(r, 20, 300),
      );

      // Spot drifts a little off the close so every day is not the same strike.
      const spot = round(sym.spot * between(r, 0.97, 1.03));
      const strike = Math.round(spot / sym.step) * sym.step;
      // An at-the-money monthly runs about 2-3% of spot at this distance from expiry.
      const entryPremium = round(Math.max(0.5, spot * between(r, 0.018, 0.032)));
      const size = sym.lotSize * LOTS;

      // The dealt outcome, and the return on premium it implies. Taken here rather than at the
      // top of the loop so a symbol clash that skips a trade does not burn a card with it.
      const outcome = deck[dealt++] ?? 'won';
      const reason: ExitReason = outcome === 'target' ? 'target'
        : outcome === 'stop' ? 'stop'
          : outcome === 'untracked' ? 'untracked'
            : 'square-off';
      const ret = outcome === 'target' ? TP
        : outcome === 'stop' ? -SL
          : outcome === 'untracked' ? 0
            : outcome === 'won' ? between(r, 0.04, 0.55)
              : between(r, -0.42, -0.02);

      // Excursions have to bracket the outcome, or the shadow rules below read as nonsense.
      const mfePct = reason === 'target' ? round(between(r, TP, TP + 0.45), 4)
        : reason === 'stop' ? round(between(r, 0.02, 0.34), 4)
          : round(Math.max(0.03, ret) + between(r, 0.04, 0.38), 4);
      const maePct = reason === 'stop' ? round(between(r, -SL - 0.12, -SL), 4)
        : reason === 'target' ? round(between(r, -0.30, -0.04), 4)
          : round(Math.min(-0.03, ret) - between(r, 0.04, 0.34), 4);

      const exitMinute = Math.min(SQUARE_OFF_MIN, Math.max(entryMinute + 6, Math.round(
        reason === 'target' ? between(r, 60, 330)
          : reason === 'stop' ? between(r, 30, 300)
            : SQUARE_OFF_MIN,
      )));

      const untracked = reason === 'untracked';
      const exitPremium = untracked ? 0 : round(Math.max(0.05, entryPremium * (1 + ret)));

      const amountUsed = round(entryPremium * size);
      const grossPnl = untracked ? null : round((exitPremium - entryPremium) * size);
      const charges = untracked ? null : round(CHARGE_PER_LOT * LOTS);
      const netPnl = grossPnl === null ? null : round(grossPnl - (charges ?? 0));
      const netPct = netPnl === null ? null : round(netPnl / amountUsed, 4);

      // What the alternative pairs would have made on the same path. A pair whose stop and target
      // were both reached is graded as the stop — the candle cannot say which came first, and
      // guessing the profitable one is how a sample journal starts flattering itself.
      const shadow = untracked ? [] : SHADOW.map((s) => {
        const outcome = maePct <= -s.sl ? 'stop' as const
          : mfePct >= s.tp ? 'target' as const
            : 'close' as const;
        return {
          name: s.name,
          pct: outcome === 'stop' ? -s.sl : outcome === 'target' ? s.tp : round(ret, 4),
          out: outcome,
          minute: outcome === 'close' ? SQUARE_OFF_MIN : Math.round(between(r, entryMinute + 5, exitMinute)),
        };
      });

      const readings: Record<string, number | null> = channel === 'displacement'
        ? {
          rvol: round(between(r, 5, 14)), rangeAtr: round(between(r, 1.0, 2.4)),
          moveAtr: round(between(r, 0.5, 1.8)), offExtremeAtr: round(between(r, 0, 0.35)),
          atr: round(spot * between(r, 0.018, 0.03)), turnoverCr: round(between(r, 100, 900), 1),
          changePct: round(between(r, -6, 6)),
        }
        : channel === 'trend-day'
          ? {
            conviction: round(between(r, 82, 94), 1), changePct: round(between(r, -5, 5)),
            atrUsed: round(between(r, 1.2, 2.6)), minutesSinceExtreme: Math.round(between(r, 0, 40)),
          }
          : { entryQuality: round(between(r, 80, 96), 1), changePct: round(between(r, -4, 4)) };

      const at = atOf(day, entryMinute);
      out.push({
        id: `${day}:${channel}:${sym.symbol}`,
        day, channel, symbol: sym.symbol, direction,
        contract: {
          label: `${strike} ${type}`,
          strike,
          type,
          instrumentKey: `${KEY_MARKER}${sym.symbol}-${strike}${type}`,
          expiry: EXPIRY,
          lotSize: sym.lotSize,
        },
        lots: LOTS,
        entry: { at, minute: entryMinute, premium: entryPremium, spot, source: 'auto' },
        exit: {
          at: atOf(day, exitMinute),
          minute: exitMinute,
          premium: exitPremium,
          spot: round(spot * (1 + (direction * ret) / 12)),
          source: 'auto',
          reason,
        },
        mark: null,
        mfePct,
        maePct,
        spreadPctAtEntry: round(between(r, 0.6, 4.5)),
        amountUsed, grossPnl, charges, netPnl, netPct,
        shadow,
        readings,
        note: `${MARKER}, not a real trade`,
        status: 'closed',
        settled: true,
        edited: false,
        updatedAt: at,
      });
    }
  });

  decorate(out);
  return out;
}

/**
 * Force the three row states the random draw will not reliably produce, so every branch of the
 * table renderer is on screen: one still open, one with a hand-typed fill, one never priced.
 *
 * The open row is deliberately NOT on the most recent day, and is flagged `settled: true`. Both
 * matter: `journalTick` marks and squares off TODAY's open rows against the live feed, and
 * `journalSettleDue` re-derives an exit from candles for anything unsettled — either would
 * overwrite these invented numbers with a lookup against a contract that does not exist.
 */
function decorate(rows: JournalTrade[]): void {
  const open = rows[Math.floor(rows.length * 0.35)];
  if (open) {
    open.exit = null;
    open.status = 'open';
    open.settled = true;
    open.mark = {
      at: atOf(open.day, SQUARE_OFF_MIN),
      premium: round(open.entry.premium * 1.24),
      pct: 0.24,
    };
    open.grossPnl = null; open.charges = null; open.netPnl = null; open.netPct = null;
  }

  const edited = rows[Math.floor(rows.length * 0.6)];
  if (edited?.exit) {
    edited.original = {
      entry: { ...edited.entry, premium: round(edited.entry.premium * 0.97) },
      exit: { ...edited.exit, premium: round(edited.exit.premium * 1.04), reason: 'square-off' },
    };
    edited.edited = true;
    edited.entry.source = 'manual';
    edited.exit.source = 'manual';
    edited.exit.reason = 'manual';
  }

  const dead = rows[Math.floor(rows.length * 0.8)];
  if (dead?.exit) {
    dead.exit = { ...dead.exit, premium: 0, reason: 'untracked' };
    dead.shadow = [];
    dead.grossPnl = null; dead.charges = null; dead.netPnl = null; dead.netPct = null;
  }
}

/* --------------------------------------------------------------------------- the disk --- */

interface Month { month: string; trades: JournalTrade[] }

const monthFile = (month: string): string => path.join(CACHE, `journal_${month}.json`);

async function readJson<T>(file: string): Promise<T | null> {
  try { return JSON.parse(await fs.readFile(file, 'utf8')) as T; } catch { return null; }
}

async function writeJson(file: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(file), { recursive: true });
  const tmp = `${file}.${process.pid}.tmp`;
  await fs.writeFile(tmp, JSON.stringify(value), 'utf8');
  await fs.rename(tmp, file);
}

function byMonth(rows: JournalTrade[]): Map<string, JournalTrade[]> {
  const m = new Map<string, JournalTrade[]>();
  for (const t of rows) {
    const k = t.day.slice(0, 7);
    m.set(k, [...(m.get(k) ?? []), t]);
  }
  return m;
}

/* ------------------------------------------------------------------------ the actions --- */

async function seed(rows: JournalTrade[]): Promise<void> {
  for (const [month, mine] of byMonth(rows)) {
    const file = monthFile(month);
    const doc = (await readJson<Month>(file)) ?? { month, trades: [] };
    const ids = new Set(mine.map((t) => t.id));
    doc.trades = [...doc.trades.filter((t) => !ids.has(t.id)), ...mine]
      .sort((a, b) => (a.day < b.day ? -1 : a.day > b.day ? 1 : a.entry.at - b.entry.at));
    await writeJson(file, doc);
    console.log(`  wrote ${mine.length} sample rows to .cache/momentum/journal_${month}.json`);
  }
}

/**
 * A row this tool wrote, however long ago, whatever the generator looked like then, and whether or
 * not someone has since edited its prices or cleared its note.
 */
const isSample = (t: JournalTrade): boolean =>
  (t.contract?.instrumentKey ?? '').startsWith(KEY_MARKER) || (t.note ?? '').startsWith(MARKER);

async function clear(): Promise<void> {
  const removedIds: string[] = [];

  for (const month of SWEEP_MONTHS) {
    const file = monthFile(month);
    const doc = await readJson<Month>(file);
    if (!doc) continue;
    const before = doc.trades.length;
    for (const t of doc.trades) if (isSample(t)) removedIds.push(t.id);
    doc.trades = doc.trades.filter((t) => !isSample(t));
    const removed = before - doc.trades.length;
    if (removed === 0) { console.log(`  journal_${month}.json — no sample rows`); continue; }
    if (doc.trades.length === 0) {
      await fs.unlink(file).catch(() => {});
      console.log(`  removed ${removed} sample rows — journal_${month}.json is now empty, deleted`);
    } else {
      await writeJson(file, doc);
      console.log(`  removed ${removed} sample rows — ${doc.trades.length} real rows kept in journal_${month}.json`);
    }
  }
  const ids = new Set(removedIds);

  // The retry queue names ids the mirror still owes the database. Leaving deleted ids in it makes
  // every later flush try to push rows that no longer exist.
  const pendingFile = path.join(CACHE, 'journal_pending.json');
  const pending = await readJson<{ ids: string[] }>(pendingFile);
  if (pending?.ids?.length) {
    const kept = pending.ids.filter((id) => !ids.has(id));
    if (kept.length !== pending.ids.length) {
      await writeJson(pendingFile, { ids: kept });
      console.log(`  dropped ${pending.ids.length - kept.length} sample ids from the push queue`);
    }
  }

  // Neon, because opening the page pushes local history there. See the header.
  if (!databaseUrl()) {
    console.log('  DATABASE_URL is not set — disk was the only copy');
    return;
  }
  try {
    // Matched on the markers rather than only the ids just swept off disk: a row that reached Neon
    // and was then removed locally by hand would otherwise have no id left to delete it by.
    // `starts_with` rather than LIKE, so nothing in a marker is read as a wildcard.
    const res = await getPool().query(
      `DELETE FROM momentum_journal
        WHERE starts_with(trade->'contract'->>'instrumentKey', $1)
           OR starts_with(trade->>'note', $2)
           OR id = ANY($3::text[])`,
      [KEY_MARKER, MARKER, [...ids]],
    );
    console.log(`  deleted ${res.rowCount ?? 0} sample rows from Neon`);
  } catch (e) {
    console.error(`  COULD NOT REACH NEON — ${(e as Error).message}`);
    console.error('  Sample rows may still be in the database. Re-run --clear when it is reachable.');
  } finally {
    await closePool();
  }
}

/* ----------------------------------------------------------------------------- main --- */

if (process.argv.includes('--clear')) {
  console.log('\n  Removing trade journal sample data\n');
  await clear();
  console.log('\n  Done. Reload /trade-journal to confirm it is gone.\n');
} else {
  const rows = build();
  console.log(`\n  Trade journal sample data — ${rows.length} rows, ${FROM} to ${TO}\n`);
  await seed(rows);
  const done = rows.filter((t) => t.netPnl !== null);
  const wins = done.filter((t) => (t.netPnl ?? 0) > 0).length;
  const net = done.reduce((a, t) => a + (t.netPnl ?? 0), 0);
  console.log(
    `\n  ${done.length} priced · ${wins}W/${done.length - wins}L ` +
    `(${((100 * wins) / Math.max(1, done.length)).toFixed(0)}%) · net ${net < 0 ? '-' : '+'}Rs ${Math.abs(net).toFixed(0)}`,
  );
  console.log('\n  EVERY ROW IS INVENTED. Remove with: npm run seed-journal -- --clear\n');
}
